@echo off
REM Build script for Windows deployment

echo Creating logs directory if it doesn't exist...
mkdir logs 2>nul

echo Installing dependencies...
pip install -r requirements.txt

echo Collecting static files...
python manage.py collectstatic --no-input

echo Running migrations...
python manage.py migrate

echo Creating cache table...
python manage.py createcachetable || echo Failed to create cache table, continuing...

echo Populating database with initial data...
python post_deploy.py

echo Build completed successfully!