#!/usr/bin/env bash
# exit on error
set -o errexit

# Create logs directory if it doesn't exist
echo "Creating logs directory if it doesn't exist..."
mkdir -p logs

# Install dependencies
echo "Installing dependencies..."
pip install -r requirements.txt

# Collect static files
echo "Collecting static files..."
python manage.py collectstatic --no-input

# Run migrations
echo "Running migrations..."
python manage.py migrate

echo "Build completed successfully!"