# Cloudflare Wrangler Configuration for Pages & Workers
name = "portfolio-website"
compatibility_date = "2026-07-27"
pages_build_output_dir = "./staticfiles"

[assets]
directory = "./staticfiles"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"
