# Generated by Django 5.2.6 on 2025-09-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Leave empty if certification does not expire', null=True)),
                ('credential_id', models.CharField(blank=True, help_text='Certification ID or badge number', max_length=100)),
                ('credential_url', models.URLField(blank=True, help_text='URL to verify certification')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-certificate', help_text='Font Awesome icon class', max_length=50)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='education',
            name='icon',
            field=models.CharField(default='fas fa-graduation-cap', help_text='Font Awesome icon class', max_length=50),
        ),
    ]
