# Generated by Django 5.2.6 on 2025-09-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated list of technologies/tools used (e.g., Burp Suite, ISO 27001, Kali Linux, Metasploit, NIST, Nessus, Nmap, OWASP)', max_length=300),
        ),
    ]
