# Generated by Django 5.2.6 on 2025-09-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_achievement_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person giving testimonial', max_length=100)),
                ('position', models.CharField(help_text='Job title or role', max_length=100)),
                ('company', models.CharField(help_text='Company or organization name', max_length=100)),
                ('content', models.TextField(help_text='The testimonial content/quote')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this testimonial')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
