# Generated by Django 5.2.6 on 2025-09-09 03:24

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cv_document',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume document (PDF, DOC, DOCX)', null=True, upload_to='cv/', validators=[main.validators.validate_cv_upload]),
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_failed', 'Failed Login Attempt'), ('login_success', 'Successful Login'), ('admin_access', 'Admin Panel Access'), ('contact_submission', 'Contact Form Submission'), ('rate_limit', 'Rate Limit Violation'), ('suspicious_request', 'Suspicious Request'), ('file_upload', 'File Upload'), ('security_scan', 'Security Scan Detected')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='main_securi_event_t_ae3c4d_idx'), models.Index(fields=['ip_address', 'created_at'], name='main_securi_ip_addr_9965ea_idx'), models.Index(fields=['severity', 'created_at'], name='main_securi_severit_b3a3ae_idx')],
            },
        ),
    ]
