# Generated by Django 5.2.6 on 2025-09-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userprofile_cv_document_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this achievement'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, help_text='Leave empty if certification does not expire', null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools & Technologies'), ('soft', 'Soft Skills')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(db_index=True, help_text='Company or organization name', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this testimonial'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(db_index=True, help_text='Full name of the person giving testimonial', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(db_index=True, help_text='Job title or role', max_length=100),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['order'], name='main_achiev_order_34f6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['is_active'], name='main_achiev_is_acti_17a462_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['created_at'], name='main_achiev_created_64e93d_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['issue_date'], name='main_certif_issue_d_ad31ae_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['name'], name='main_certif_name_c66db6_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['issuing_organization'], name='main_certif_issuing_35c974_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['created_at'], name='main_contac_created_619d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['email'], name='main_contac_email_0c510f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['subject'], name='main_contac_subject_aaa500_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['start_date'], name='main_educat_start_d_1c0f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['institution'], name='main_educat_institu_4f1731_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['degree'], name='main_educat_degree_7feecb_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['start_date'], name='main_experi_start_d_6dc3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['company'], name='main_experi_company_d33bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['position'], name='main_experi_positio_ab2e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='main_skill_categor_2d3bef_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='main_skill_name_9a51d7_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['order'], name='main_testim_order_b64968_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_active'], name='main_testim_is_acti_90047b_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['created_at'], name='main_testim_created_30d19a_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['company'], name='main_testim_company_32f9ae_idx'),
        ),
    ]
