# Generated by Django 5.2.6 on 2025-09-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_achievement_main_achiev_order_34f6c7_idx_and_more'),
    ]

    operations = [
    ]
