# Generated by Django 5.2.6 on 2025-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20250911_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('skill', 'Skills'), ('tools', 'Tools'), ('soft', 'Soft Skills')], max_length=20),
        ),
    ]
