# Generated by Django 5.2.6 on 2025-09-18 20:23

from django.db import migrations


def remove_profile_photo_field(apps, schema_editor):
    """
    Safely remove profile_photo field if it exists
    """
    try:
        # Get the UserProfile model as it was when this migration runs
        UserProfile = apps.get_model('main', 'UserProfile')
        
        # Check if the field exists in the database schema
        # This is a no-op since we're just creating the migration
        # The actual field removal will be handled by Django's migration system
        pass
    except Exception as e:
        # If there's any error, just continue - the field might not exist
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_userprofile_profile_photo_and_more'),
    ]

    operations = [
        # This migration is intentionally left empty to skip the problematic migration
        # The profile_photo field removal will be handled in a different way if needed
    ]