# Generated by Django 5.2.6 on 2025-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='writeup_document',
            field=models.FileField(blank=True, help_text='Project writeup or report (PDF, DOC, DOCX)', upload_to='projects/writeups/'),
        ),
    ]
