# Generated by Django 5.2.6 on 2025-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_category_name_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='portfolio_c_name_f2e04c_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='portfolio_c_slug_75da1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='portfolio_p_is_feat_73f62f_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='portfolio_p_created_6dcf92_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='portfolio_p_updated_dddcda_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='portfolio_p_status_e2a3b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='portfolio_p_slug_e96b08_idx',
        ),
        migrations.RemoveIndex(
            model_name='technology',
            name='portfolio_t_name_9d980b_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
